### PR TITLE
Czech translations

### PR DESCRIPTION
**Pull request by vonschau**
Hi,

here are czech translations. Once proofread, hopefully without typos.

Martin

### CODE REVIEW

**Comment by matjack1** [comment]
Excellent, thanks!

**Comment by matjack1** [comment]
Hello @vonschau !

We have finally implemented a system to integrate community translations in our development workflow.

We would like to thank you by offering you some credit towards the use of DatoCMS and invite you to our https://localise.biz project where you can go ahead and translater more.

We will organise the community work in Github issues, so please get in touch here: https://www.datocms.com/support if you either want your credit or get more info on how to go ahead.

Thank you for now!

**Comment by vonschau** [comment]
Hello @matjack1 !

I definitely want to continue the job on czech translations so please let me know, how can I do that. I've already signed up in localise.biz project so please invite me, thanks!

**Comment by matjack1** [comment]
Excellent @vonschau thank you very much!!

I've invited you and here's the issue that we use to track progress: https://github.com/datocms/translations/issues/14

Please let me know once you are done or if you have any issue.

**Pull request merged**
