### PR TITLE
add the french translation

### PR DESCRIPTION
**Pull request by Timdev0**

### CODE REVIEW

**Review by TotomInc — APPROVED** [review]
As a native french speaker, this looks good for me!

**Comment by matjack1** [comment]
Thank you both! We are going to get this live soon :)

**Comment by stefanoverna** [comment]
Should be already online!

**Comment by TotomInc** [comment]
I can confirm it's online, DatoCMS looks really great in french!

You can safely merge the PR! 😄

**Comment by matjack1** [comment]
Hello @Timdev0 and @TotomInc !

We have finally implemented a system to integrate community translations in our development workflow.

We would like to thank you by offering you some credit towards the use of DatoCMS and invite you to our https://localise.biz project where you can go ahead and translater more.

We will organise the community work in Github issues, so please get in touch here: https://www.datocms.com/support if you either want your credit or get more info on how to go ahead.

Thank you for now!

**Pull request merged**
